# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-1"
      with:
#         # AWS Access Key ID. This input is required if running in the GitHub hosted environment. It is optional if running in a self-hosted environment that already has AWS credentials, for example on an EC2 instance.
        aws-access-key-id: $AWS_ACCESS_KEY_ID
#         # AWS Secret Access Key. This input is required if running in the GitHub hosted environment. It is optional if running in a self-hosted environment that already has AWS credentials, for example on an EC2 instance.
        aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
#         # AWS Session Token
#         aws-session-token: # optional
#         # AWS Region, e.g. us-east-2
        aws-region: us-east-1
#         # Whether to set the AWS account ID for these credentials as a secret value, so that it is masked in logs. Valid values are 'true' and 'false'. Defaults to true
#         mask-aws-account-id: # optional
#         # Use the provided credentials to assume an IAM role and configure the Actions environment with the assumed role credentials rather than with the provided credentials
#         role-to-assume: # optional
#         # Role duration in seconds (default: 6 hours)
#         role-duration-seconds: # optional
#         # Role session name (default: GitHubActions)
#         role-session-name: # optional
#         # The external ID of the role to assume
#         role-external-id: # optional
#         # Skip session tagging during role assumption
#         role-skip-session-tagging: # optional

    - name: S3 Deploy
      uses: Reggionick/s3-deploy@v2.0.0
#       with:
#         # Directory to deploy
#         folder: 
#         # Name of AWS Bucket
#         bucket: 
#         # AWS CloudFront distribution ID
#         dist-id: 
#         # AWS CloudFront invalidation path(s)
#         invalidation: 


#     # Runs a single command using the runners shell
#     - name: Run a one-line script
#       run: echo Hello, world!
    
#     - name: NodeJS Action Template
#       uses: bitoiu/node-js-action-template@v1.0

#     # Runs a set of commands using the runners shell
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
